/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PaywallRouteImport } from './routes/paywall'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedReportRouteImport } from './routes/_authenticated.report'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedCategorizeRouteImport } from './routes/_authenticated.categorize'
import { Route as ApiPublicSuggestCategoryRouteImport } from './routes/api/public/suggest-category'
import { Route as ApiPublicSendOtpEmailRouteImport } from './routes/api/public/send-otp-email'
import { Route as ApiPublicCategorizeFileRouteImport } from './routes/api/public/categorize-file'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PaywallRoute = PaywallRouteImport.update({
  id: '/paywall',
  path: '/paywall',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportRoute = AuthenticatedReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCategorizeRoute = AuthenticatedCategorizeRouteImport.update({
  id: '/categorize',
  path: '/categorize',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicSuggestCategoryRoute =
  ApiPublicSuggestCategoryRouteImport.update({
    id: '/api/public/suggest-category',
    path: '/api/public/suggest-category',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSendOtpEmailRoute = ApiPublicSendOtpEmailRouteImport.update({
  id: '/api/public/send-otp-email',
  path: '/api/public/send-otp-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCategorizeFileRoute = ApiPublicCategorizeFileRouteImport.update({
  id: '/api/public/categorize-file',
  path: '/api/public/categorize-file',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/paywall': typeof PaywallRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/categorize': typeof AuthenticatedCategorizeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/report': typeof AuthenticatedReportRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/public/categorize-file': typeof ApiPublicCategorizeFileRoute
  '/api/public/send-otp-email': typeof ApiPublicSendOtpEmailRoute
  '/api/public/suggest-category': typeof ApiPublicSuggestCategoryRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/paywall': typeof PaywallRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/categorize': typeof AuthenticatedCategorizeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/report': typeof AuthenticatedReportRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/categorize-file': typeof ApiPublicCategorizeFileRoute
  '/api/public/send-otp-email': typeof ApiPublicSendOtpEmailRoute
  '/api/public/suggest-category': typeof ApiPublicSuggestCategoryRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/paywall': typeof PaywallRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/categorize': typeof AuthenticatedCategorizeRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/report': typeof AuthenticatedReportRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/categorize-file': typeof ApiPublicCategorizeFileRoute
  '/api/public/send-otp-email': typeof ApiPublicSendOtpEmailRoute
  '/api/public/suggest-category': typeof ApiPublicSuggestCategoryRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/paywall'
    | '/privacy'
    | '/terms'
    | '/categorize'
    | '/dashboard'
    | '/report'
    | '/settings'
    | '/api/public/categorize-file'
    | '/api/public/send-otp-email'
    | '/api/public/suggest-category'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/onboarding'
    | '/paywall'
    | '/privacy'
    | '/terms'
    | '/categorize'
    | '/dashboard'
    | '/report'
    | '/settings'
    | '/'
    | '/api/public/categorize-file'
    | '/api/public/send-otp-email'
    | '/api/public/suggest-category'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/paywall'
    | '/privacy'
    | '/terms'
    | '/_authenticated/categorize'
    | '/_authenticated/dashboard'
    | '/_authenticated/report'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/api/public/categorize-file'
    | '/api/public/send-otp-email'
    | '/api/public/suggest-category'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  PaywallRoute: typeof PaywallRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiPublicCategorizeFileRoute: typeof ApiPublicCategorizeFileRoute
  ApiPublicSendOtpEmailRoute: typeof ApiPublicSendOtpEmailRoute
  ApiPublicSuggestCategoryRoute: typeof ApiPublicSuggestCategoryRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paywall': {
      id: '/paywall'
      path: '/paywall'
      fullPath: '/paywall'
      preLoaderRoute: typeof PaywallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/report': {
      id: '/_authenticated/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AuthenticatedReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/categorize': {
      id: '/_authenticated/categorize'
      path: '/categorize'
      fullPath: '/categorize'
      preLoaderRoute: typeof AuthenticatedCategorizeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/suggest-category': {
      id: '/api/public/suggest-category'
      path: '/api/public/suggest-category'
      fullPath: '/api/public/suggest-category'
      preLoaderRoute: typeof ApiPublicSuggestCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-otp-email': {
      id: '/api/public/send-otp-email'
      path: '/api/public/send-otp-email'
      fullPath: '/api/public/send-otp-email'
      preLoaderRoute: typeof ApiPublicSendOtpEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/categorize-file': {
      id: '/api/public/categorize-file'
      path: '/api/public/categorize-file'
      fullPath: '/api/public/categorize-file'
      preLoaderRoute: typeof ApiPublicCategorizeFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCategorizeRoute: typeof AuthenticatedCategorizeRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedReportRoute: typeof AuthenticatedReportRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCategorizeRoute: AuthenticatedCategorizeRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedReportRoute: AuthenticatedReportRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  PaywallRoute: PaywallRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiPublicCategorizeFileRoute: ApiPublicCategorizeFileRoute,
  ApiPublicSendOtpEmailRoute: ApiPublicSendOtpEmailRoute,
  ApiPublicSuggestCategoryRoute: ApiPublicSuggestCategoryRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
